### ISSUE TITLE
Is there a functionality to produce interpolated scatterplots over a user-specific lat/lon extent?

### ISSUE THREAD

**Issue by ksd3** [dinsmoro/GRITI#1]
I believe this functionality could be extracted from the keograms but I can't quite figure out how to

**Comment by dinsmoro** [comment]
How are you envisioning the interpolated scatter plots to work/look? The keograms already have an interpolation flag around line 773, which works well for the gridded keogram data, if that helps.

**Comment by ksd3** [comment]
So, I don't want a keogram - I want to just take Madrigal TEC observations around any lat/lon 'square' of the Earth's surface and fill in the missing values in a physically meaningful way. I currently do this by standard methods - binning them to a matrix and interpolating it, but I have no way to know whether my interpolations make physical sense. While this problem is in some sense beyond the scope of GRITI, I was hoping that GRITI had some functionality that got me plots like
![this](https://github.com/dinsmoro/GRITI/assets/89213519/2936d7fb-d4ed-4545-8098-bfa413e621da)

My problem is that while Madrigal provides averaged 5-minute plots, I need to work with the 30 second plots for phenomena I'm investigating, and I was hoping GRITI provided some tools that could help.

**Comment by dinsmoro** [comment]
Gotchya, yea there's a function for that, amazingly. Down in the "Movie Snaps" section does that (it's rough around the edges, but so is everything in this rn).

These settings should be the easiest:
```
snaps_type = 1
snaps_auto = 2
snaps_auto_start = 'auto'; #hr, auto starts at beginning of the day, put an hour in (wrt 0 hour) if you want something specific
snaps_auto_step = 0.5;' #min, time to step
snaps_auto_end = 'auto'; #hr, auto ends at end of the day, put an hour in (wrt 0 hour) if you want something specific
```

Let me know if the decimal minute causes issues, sometimes the floating point error really mucks with time stuff.

I think it'll only save the plots in the "Plots" folder, they won't be interactive. If you need that I can add in an option for that.

It'll batch them up into multiple subplots per plot, if you want them single let me know and I'll add in a mode to force that.

I can hook up the interpolation function used by the keograms to it to when I get a chance - it works via RBF and is as robust as I think you can get without an interpolation method that involves ionospheric modeling to inform it better or something.

If you wanted actual scatter dots, that's technically snaps_type=0 which doesn't exist yet (mirrors movieType listing). I can also add that when I get a chance, if you want scatter dots. But I'm not sure how to choose where to interpolate new points since the data isn't on a nice grid.

**Comment by dinsmoro** [comment]
Download the latest GRITI_main.py, I made sure movie_snaps works for type 1 and added in single plot/interactive/interpolation and made the times second-based (should prevent timing issues). Let me know if that is workable for you!

**Comment by ksd3** [comment]
I'm still a bit confused - the variables snaps_auto_start seem to be initialized at multiple places. Where exactly should I change the settings, or should I use a config file?

**Comment by dinsmoro** [comment]
The config file is lightly used atm, so you set stuff for this in the GRITI_main at the snaps section (line 1427 onward). Sometimes extra declarations of the same variable end up from rapid testing, you can just delete the lines between the `snaps_type` declaration and `snaps_dayNiteLine` declaration and replace them with

```
snaps_auto = 2; #if 0, uses snaps_Times | 1 will generate them from snaps_auto & steps to take | 2 will generate from 
snaps_auto_start = 0*3600; #sec, time to start [-11, 20 min steps, 6 steps is nice too], 'auto' chooses the start time as the start edge automagically
snaps_auto_step = 30; #sec, time to step
snaps_auto_end = 1*3600+30; #sec, time to end *for snaps_auto == 2*, 'auto' chooses the end time as the end edge automagically (does not include last time step! e.g., 0 to 90 at 30 step will yield 0, 30, 60 steps)
```

Those settings will start at 0 hr and make a plot every 30 seconds until hour 1 (wrt zero-hour). The +30 makes it also make a plot on hour 1 itself since it's end is non-inclusive. It should make 120 plots

Cribbing from the [`numpy arange` docs](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) (which it mimics how that works):
snaps_times generated in (`snaps_auto_start`, `snaps_auto_end`, `snaps_auto_step`) Values are generated within the half-open interval [`snaps_auto_start`, `snaps_auto_end`), with spacing between values given by `snaps_auto_step`.

The settings at the bottom:
```
FLG_snaps_interpolate = True; # Interpolates gaps in each snap
FLG_snaps_forceSinglePlot = True; # False batches multiple subplots into a single plot, True forces a single subplot per plot - useful for high time resolution imaging
FLG_snaps_forceInteractive = True; # False does not show the snap plots and just saves them (higher resolution, better control, etc), True shows each snap plot (limited to monitor size) - best use is with "force single plot" above.
```
Let you declare if you want the plots to be interactive or saved to the Plots folder, if you want 1 subplot per plot or you want to let it put multiple subplots on a plot, and if you want it to interpolate the gridded data.

I've noticed that the grid seems to go past the edges of the plot, I'll look at that in a bit - pcolormesh can get feisty sometimes.

**Comment by dinsmoro** [comment]
Paste this between the `snaps_type` declaration and `snaps_dayNiteLine` declaration instead, I cleaned it up and put them with their respective parts. Should make it easier if you wanted to try another way.

```
# --- For snaps_auto == 0 ---
# Declare your own specific times
# snaps_times = [ 16*3600, 17*3600, 18*3600, 19*3600 ]; #sec, input some times in sec for when to take snaps - best way is to make a movie, then choose the times

# --- For snaps_auto == 1 ---
# Automatically generate based on a snaps_auto_start start time, snaps_auto_step step amount, and number of steps to take snaps_auto_stepsToTake
# snaps_auto_start = -16*3600; #sec, time to start
# snaps_auto_step = 30*60; #sec, time to step
# snaps_auto_stepsToTake = 12; #steps to take after the start

# --- For snaps_auto == 2 ---
# Automatically generate based on a snaps_auto_start start time, snaps_auto_step step amount, and end time of snaps_auto_end (non-inclusive with respect to the end time)
snaps_auto_start = 0*3600; #sec, time to start, 'auto' chooses the start time as the start edge automagically
snaps_auto_step = 30; #sec, time to step
snaps_auto_end = 1*3600+30; #sec, time to end *for snaps_auto == 2*, 'auto' chooses the end time as the end edge automagically (does not include last time step! e.g., 0 to 90 at 30 step will yield 0, 30, 60 steps)
```

Hope it's something that helps you!

Edit:
Also note that my code runs on debiased vTEC (delta-vTEC) not vTEC itself. If you need vTEC I can add a flag for that, but that'll be a bit longer to get it coded in.

**Comment by ksd3** [comment]
I don't quite understand what delta-vTEC is. I read the paper but it seemed like something the reader should already know. What is a layman's explanation of delta-vTEC?

**Comment by ksd3** [comment]
Also, turns out that even by installing aacgmv2 on Mac, the code throws an error.

**Comment by dinsmoro** [comment]
delta-vTEC is debiased vTEC, which means the moving average is subtracted from the vTEC. Basically it goes slant TEC (actual measurement from the receiver) -> vertical TEC (slant corrected via model to be uniformally 90 degrees up) -> delta vTEC (moving average on a several hour timescale subtracted from vTEC to yield just the higher frequency activity)

Essentially, the delta-vTEC removes the daily vTEC variations from the Sun (not fully) to give you whatever remains - which is the interesting stuff.

As for on a Mac, I've never run it on there. It works on Windows and it likely works on Linux - you can paste the stack trace it complains about here if you like and I can see if it's something in GRITI or just aacgmv2.

**Comment by ksd3** [comment]
The error is just 'couldn't locate aacgmv2' - namely, even though I successfully ran pip install aacgmv2, the package isn't getting imported. I think this is something I'd have to figure out - but what you said about delta-vTEC seems exactly like the quantity I want. Instead of producing movies, is there a way I can just get an ndarray or a list of lon/lat/delta-vTEC values every 30 seconds? Currently I do it by looping through the Line-of-Sight Madrigal TEC HDF5 files, which is extremely slow. It would be really helpful to get them from GRITI since GRITI does a conversion to a faster-to-read hdf5 form.

**Comment by dinsmoro** [comment]
You'd probably have to roll your own for that - but you can use GRITI functions. You can use `GRITI_import_TEC_Madrigal` (as well as `GRITI_import_TEC_support` and a bunch of the `subfuns_` so just bring them all along)  to ensure the files are there (or it'll automagically get them and make the faster versions first) and then you can have your current code that looks through the Madrigal HDF5 files loop through those. You need to have all the functions in a subfolder named `Code` wrt the script you're running since that's what they expect.

You just need the inputs formed like so to call `GRITI_import_TEC_Madrigal` successfully:
```
import numpy as np
from psutil import cpu_count
from Code.GRITI_import_TEC_Madrigal import GRITI_import_TEC_Madrigal
from Code.subfun_date_to_dayNum import subfun_date_to_dayNum
from Code.subfun_dateORdayNum_to_fullRange import subfun_dateORdayNum_to_fullRange

# --- user settings ---
dateRange = np.array([[2017,6,6],[2017,6,9]],dtype="int16"); #dates are in int16 because they can be
plotLatRange = [-90, 90]; #latitude limit - if you ignore the output of GRITI_import_TEC_Madrigal it won't matter what this is
plotLongRange = [-180, 180]; #longitude limit - if you ignore the output of GRITI_import_TEC_Madrigal it won't matter what this is

# prep work
dateRange_dayNum = subfun_date_to_dayNum(dateRange); #call function to get the date range into dayNumber form (easy to work with)
(_, dateRange_dayNum_full) = subfun_dateORdayNum_to_fullRange(dateRange_dayNum); #call fun to get fully enumerated days between range
dateRange_dayNum_zeroHr = dateRange_dayNum_full[np.int16( np.floor((len(dateRange_dayNum_full[:,0]) - 1)/2) ),:]; #choose day for when "0 hr" is - makes plots nice, no day units just hr units

dates = {
    'date range full dayNum': dateRange_dayNum_full,
    'date range zero hr dayNum': dateRange_dayNum_zeroHr,
}

settings = {
    'paths': {
        'data': '<path to where you want data stored>',
    },
    'config': {
        'login Madrigal': {
            'name': '<your name>'.replace(' ','+'),
            'email': '<your email>'.replace(' ','+'),
            'affil': '<your affiliation>'.replace(' ','+'),
        },
        'parallel num threads': cpu_count(logical = True),
    },
    'map' : {'coord type': 'geo'},
}

settings_config = settings['config']
settings_TEC_import = { 
    'TEC_maxAmpAllowed':2, #TECU, max val allowed - it is a forced cutoff value (ref data had a max of 396 it seems)
    'TEC_timeTolerance':0.1, #0.1:10% so time tolerance is within 10%. So for 30 sec time steps, 10% time tolerance will make 27-33 sec time stamps be 30 sec time stamps
    'TEC_minElevation':30, #deg, [min elevation angle used to process data, min elevation angle accepted after data is processed]
    'TEC_minimumTimeGap':5*60, #sec, how long to accept a gap in a satellite observation before calling it a new, unrelated observation
    'TEC_deltaTEC_compareValue':6, #median comparator number for choosing stuff on the edges that are out of an acceptable range, inspired by https://stackoverflow.com/questions/11686720/is-there-a-numpy-builtin-to-reject-outliers-from-a-list
    'TEC_dataRate':30, #sec/datapt, the data rate. No super easy way to get it out of the data automatically, so it's a variable to control
    'filter_savGolPeriod':60*60, #sec, filter period for the Sav-Gol filter (only passes this long or longer are kept, many are not longer - very few are 3 hr long)
    'order_savGol':1, #order of the Sav-Gol fit, 3 is default, 1 is linear
    'web_base_name':settings_config['login Madrigal']['name'], #put your name here (for spaces use +'s instead)
    'web_base_email':settings_config['login Madrigal']['email'], #put your email here
    'web_base_affil':settings_config['login Madrigal']['affil'], #put your affiliation here (school etc)
    'FLG_dataAggregation':0, #0 don't aggregate nearby TEC values with a site/sat combo, 1 aggregate nearby TEC values with a site/sat combo for MORE DATA PER DATA [does not work atm, may never]
    'TEC_dataAgg_timeAdditionLimit':1*60*60, #sec, time to add on to a satellite's visible time before calling it quits
    'TEC_dataAgg_distToPts':20, #km, distance to extended points for TEC data to exist
    'TEC_dataLimPercent':0.05, #0.05:5%, cut out times with very low data content (less than 5% of the mean data content #)
    'TEC_deltaLim':0.5, #unrelated to above, value between fit/real data to find where ends of the fit where it starts diverging
    'FLG_reqPaddedDays':0, #requires padded days if 1, doesn't require them if 0
    'FLG_deleteOrig':0, #deletes original files if 1, doesn't delete original files if 0 (original being ones DL'd from Madrigal)
    'FLG_deleteUnfilt':0, #deletes unfiltered middle-stage files if 1, doesn't delete unfiltered files if 0 (makes recalc's faster if they're kept)
    'FLG_overwrite':0, #recalcs & overwrites files even if they're there if 1, doesn't recalc and uses files if they're there if 0
    'max retry':3, #number of retries for internet access errors. -1 is infinite retries
    'retry wait set':[10,30,5], #time delay for internet access errors in seconds [start delay, max delay, increment delay each retry] is the order
    'max retry file':3, #number of retries for file read errors. -1 is infinite retries [do not use here]
    'lat range': plotLatRange,
    'long range': plotLongRange,
};
settings['TEC import'] = settings_TEC_import 

data = {} # prep
# data['TEC'] = GRITI_import_TEC_Madrigal( dates, settings ) # Get the TEC data in a dict
# data['TEC']['time unique'] = np.unique(data['TEC']['time']); #sec, get unique times (v useful)
# data['TEC']['time unique aligned'] = np.unique(data['TEC']['time aligned']); #sec, get unique times (v useful) [aligned has year support and is set around the defined 0 hour]
GRITI_import_TEC_Madrigal( dates, settings ) # Alternatively, ignore output and read it in yourself later with your code!
```
(I pasted this together in the text box so it might not be OK python syntax)

Hope you can get sciencing with some of these tools!

Also, if you're not using aacgmv2 (you're not using it if you're not using geomagnetic coordinates - 'coord type' = 'mag') you can just comment out any `import aacgmv2` calls there are. W/o the import it'll only error if you were using geomagnetic coords since that's the only time aacgmv2 functions get called.

**Comment by ksd3** [comment]
This still throws an error: 
```---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[3], line 65
     34 settings_TEC_import = { 
     35     'TEC_maxAmpAllowed':2, #TECU, max val allowed - it is a forced cutoff value (ref data had a max of 396 it seems)
     36     'TEC_timeTolerance':0.1, #0.1:10% so time tolerance is within 10%. So for 30 sec time steps, 10% time tolerance will make 27-33 sec time stamps be 30 sec time stamps
   (...)
     59     'long range': plotLongRange,
     60 };
     62 # data['TEC'] = GRITI_import_TEC_Madrigal( dates, settings ) # Get the TEC data in a dict
     63 # data['TEC']['time unique'] = np.unique(data['TEC']['time']); #sec, get unique times (v useful)
     64 # data['TEC']['time unique aligned'] = np.unique(data['TEC']['time aligned']); #sec, get unique times (v useful) [aligned has year support and is set around the defined 0 hour]
---> 65 GRITI_import_TEC_Madrigal( dates, settings ) # Alternatively, ignore output and read it in yourself later with your code!

NameError: name 'dates' is not defined
```

I changed the variable ``dates`` to ``dateRange`` and it now throws an indexing error:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[4], line 65
     34 settings_TEC_import = { 
     35     'TEC_maxAmpAllowed':2, #TECU, max val allowed - it is a forced cutoff value (ref data had a max of 396 it seems)
     36     'TEC_timeTolerance':0.1, #0.1:10% so time tolerance is within 10%. So for 30 sec time steps, 10% time tolerance will make 27-33 sec time stamps be 30 sec time stamps
   (...)
     59     'long range': plotLongRange,
     60 };
     62 # data['TEC'] = GRITI_import_TEC_Madrigal( dates, settings ) # Get the TEC data in a dict
     63 # data['TEC']['time unique'] = np.unique(data['TEC']['time']); #sec, get unique times (v useful)
     64 # data['TEC']['time unique aligned'] = np.unique(data['TEC']['time aligned']); #sec, get unique times (v useful) [aligned has year support and is set around the defined 0 hour]
---> 65 GRITI_import_TEC_Madrigal( dateRange, settings ) # Alternatively, ignore output and read it in yourself later with your code!

File ~/Downloads/GRITI-main/Code/GRITI_import_TEC_Madrigal.py:90, in GRITI_import_TEC_Madrigal(dates, settings, FLG_justChecking)
     78 version_filt = GRITI_import_TEC_support_filterVersion(); #filtered algorithm version
     79 #1 10/8/2019 - initial algorithm
     80 #1.1 9/11/2020 - fixed non-0/30 time step handling (29/59 were big ones)    
     81 #1.2 9/16/2020 - removed highpass filter, only dampens data
   (...)
     88 
     89 #==============Unpack==============
---> 90 dateRange_dayNum_full = dates['date range full dayNum']; #unpack
     91 dateRange_dayNum_zeroHr = dates['date range zero hr dayNum']; #unpack
     92 settings_paths = settings['paths']; #unpack

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

I ended up looking at ``GRITI_import_TEC_Madrigal.py`` and found out that the call ``dates['date range full dayNum']`` shouldn't work regardless of my input, as ``dateRange`` is an ndarray. How should I format ``dates``?

Also, just to be clear, this part of the code only converts the Madrigal data into an easier-to-read HDF5 file, right? It doesn't produce the delta-vTEC? Or does it do that too?

**Comment by dinsmoro** [comment]
Whoops dates is a dict, forgot to pack it up!

```
dates = {
    'date range full dayNum': dateRange_dayNum_full,
    'date range zero hr dayNum': dateRange_dayNum_zeroHr,
}
```


And `GRITI_import_TEC_Madrigal` converts the Madrigal data into an HDF5 form that's faster (_unfilt_ files) and then detrends it (delta-vTEC _filtered_ files). Both have much bigger batch sizes so they read quickly.

**Comment by ksd3** [comment]
So should I add this just before the function call to ``GRITI_import_TEC_Madrigal``?

```
If yes, then my new error is ``---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[10], line 68
     61 dates = {
     62     'date range full dayNum': dateRange_dayNum_full,
     63     'date range zero hr dayNum': dateRange_dayNum_zeroHr,
     64 }
     65 # data['TEC'] = GRITI_import_TEC_Madrigal( dates, settings ) # Get the TEC data in a dict
     66 # data['TEC']['time unique'] = np.unique(data['TEC']['time']); #sec, get unique times (v useful)
     67 # data['TEC']['time unique aligned'] = np.unique(data['TEC']['time aligned']); #sec, get unique times (v useful) [aligned has year support and is set around the defined 0 hour]
---> 68 GRITI_import_TEC_Madrigal( dates, settings ) # Alternatively, ignore output and read it in yourself later with your code!

File ~/Downloads/GRITI-main/Code/GRITI_import_TEC_Madrigal.py:95, in GRITI_import_TEC_Madrigal(dates, settings, FLG_justChecking)
     93 settings_config = settings['config']; #unpack
     94 coordType = settings['map']['coord type']; #unpack
---> 95 plotLatRange = settings['TEC import']['lat range']; #unpack
     96 plotLongRange = settings['TEC import']['long range']; #unpack
     97 web_base_name = settings['TEC import']['web_base_name']; #unpack

KeyError: 'TEC import'
```

I feel like I'm doing something wrong, though - I created a new .py file to simply call GRITI_import_TEC_Madrigal. Should I insert you given snippet anywhere else?

Also, the problem with ``aacgmv2`` not being found was simply that Spyder runs on Python3.9 and my version is 3.11

**Comment by dinsmoro** [comment]
Copy https://github.com/dinsmoro/GRITI/issues/1#issuecomment-1803322790 again, I've updated to have the dates dict, and the TEC import settings included.

```
settings['TEC import'] = settings_TEC_import 

data = {} # prep
```

But like I said, the big blurb above has it all now and will run!

**Comment by ksd3** [comment]
Thanks for providing this snippet. It's almost exactly what I need. Just one question - are the dTEC values supposed to be negative for a lot of spots? That's very unrealistic, isn't it?

Edit: Just running some tests, out of 79478447 TEC values in a sample file, 43427904 are negative. Is this supposed to happen?

Edit 2: I suspect that it's something to do with the ``settings_TEC_import`` variable - since I only ran your code once, on default settings, I suspect that changing those settings will give me dTEC values that negative for a majority of values. Is there any way to predict what settings you'd need to change to get non-negative TEC values in general, or no?

**Comment by dinsmoro** [comment]
vTEC being negative wouldn't make sense, delta-vTEC being negative is just fine!

![Single Satellite Pass](https://github.com/dinsmoro/GRITI/assets/40899811/8053d6f1-e923-42dd-8294-16f2dff1557a)

This plot shows the detrending (Savitzky-Golay fit) and the vTEC itself. The fit gets subtracted off of the vTEC and the resulting delta-vTEC is roughly positive 50% of the time and negative the other 50% over a long period of time. Hope that helps!

**Comment by ksd3** [comment]
Thanks for explaining, I understand now. 

A question about the sorted files - the original Madrigal files had a ``ut1_unix`` timestamp associated to each observation. It seems like that timestamp has been removed in the filtered files - but not completely. Looking through the ``time`` column of the hdf5 file, it seems like some sort of UNIX timestamp exists, but only for that specific date? Also, it looks like the data elements are sorted by ``sat``? Is that right?

Edit: Essentially, I'm asking whether I'd have to manually convert the timestamps in the files to UNIX time, as I don't know if they're in UTC (which I assume they are)

**Comment by dinsmoro** [comment]
The times are in UTC but I did not save the Unix time wrt 1970 from the original Madrigal files. I save them as year/dayNum/hr/min/sec, so you'll have to build them however you need them. I can add that in at some point, but that'll be a bit.

The `time` in the filtered HDF5 file is the number of seconds since the start of the year, while year/dayNum/hour/min/sec are self explanatory and can get you to the Unix time (there's probably a function that converts it, or you can maths).

The data is sorted by site and then satellite, cause each Sav-Gol filter run is calculated on one satellite pass recorded by a site that records many satellite passes from many satellites, see this figure: 
![Data Array Breakdown Figure](https://github.com/dinsmoro/GRITI/assets/40899811/d5af390c-93d5-4549-abae-37648e82cd81)

I don't necessarily try to sort it by that, I just filter it in that way and save it as it is filtered so then you find it in that order!

**Comment by ksd3** [comment]
Okay, thanks! One more question - I set ``dateRange`` to ``np.array([[2021,3,14],[2021,3,14]],dtype="int16");`` and ran the snippet you gave, giving me the following files:

```
TEC_2021_72_unfilt_Madrigal.h5	los_20210313.001.h5
TEC_2021_73_Madrigal.h5         los_20210314.001.h5
TEC_2021_73_unfilt_Madrigal.h5	los_20210315.001.h5
TEC_2021_74_unfilt_Madrigal.h5
```
Essentially, the files for the 13th, 14th, and 15th of March 2021. I then got the filtered file ``TEC_2021_73_Madrigal.h5`` which should contain the TEC values for the 73rd day of 2021 i.e. Sunday March 14 2021. However, running the following code:

```
>>>import h5py
>>> f=h5py.File("TEC_2021_73_Madrigal.h5","r")
>>> f['time'][0]
6333270
>>> f['year'][0]
2021
``` 
says that the first observation was made at 6333270 seconds past the beginning of 2021.

12 AM Friday, Jan 1, 2021 is 1609459200
![image](https://github.com/dinsmoro/GRITI/assets/89213519/bab9d138-1b09-4ec5-92ed-193f0b38f70d)

and 1609459200+6333270=1615792470, which gives 
![image](https://github.com/dinsmoro/GRITI/assets/89213519/3d604fc7-f88a-4e81-b883-8c87655a90d3)

the 15th of March.
Querying ``f['dayNum'][0]`` gives 73, so what's going wrong? Am I making an off-by-one-day error somewhere?

**Comment by dinsmoro** [comment]
it's likely that the `dayNum` is 1 on jan 1st and the time calcs within a year are `dayNum*86400+hour*3600+min*60+sec` which makes it that jan 1st at 00:00:00 is 86400. I never noticed this cause the code operates on a "0 hour" derived from some earlier convention and to get that you subtract a dayNum off like `dayNum*86400+hour*3600+min*60+sec - dayNum_zeroHrRef*86400`.

So it is off by 1 day by "design", subtract off a day's worth of time so Jan 1st starts at 0 seconds in a year and it should be better!

**Comment by ksd3** [comment]
Aaaahhh, yes, that makes sense, thanks!

**Comment by ksd3** [comment]
I'm going to close this issue now; thanks for all your help. If nothing else, the conversion of Madrigal files into easier-to-access hdf5 files has been a godsend. I'm still looking for a physically-accurate way of extrapolating TEC data into missing spots but that's beyond GRITI to some extent.
